### ISSUE TITLE
项目进展

### ISSUE THREAD

**Issue by xiaolongDGitHub** [ChrisLee63/person_search#1]
请问这个项目进展到哪一步了？

**Comment by 520Chris** [comment]
很抱歉过了这么久才回复。
这个项目还在开发中，已经可以加载caffe训练好的模型，然后前向传播。
目前在调试训练模型的代码。
最终项目将会：复现原作者论文的结果，且用更少的代码。
PS：原作者的代码是基于Ross Girshick的faster-rcnn写的，代码里有很多fast-rcnn时代冗余的代码，

**Comment by xiaolongDGitHub** [comment]
哈哈，没事没事，我找了好几个就是没有pytorch的，caffe的一跑通啥都看不见，然后找了个pytorch的OIMloss，还是没有弄出来，加油加油------------------ 原始邮件 ------------------
发件人: "Zj Li"<notifications@github.com>
发送时间: 2020年2月1日(星期六) 晚上11:06
收件人: "520Chris/person_search"<person_search@noreply.github.com>;
抄送: "xiaolongDGitHub"<835194085@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [520Chris/person_search] 项目进展 (#1)



很抱歉过了这么久才回复。
 这个项目还在开发中，已经可以加载caffe训练好的模型，然后前向传播。
 目前在调试训练模型的代码。
 最终项目将会：复现原作者论文的结果，且用更少的代码。
 PS：原作者的代码是基于Ross Girshick的faster-rcnn写的，代码里有很多fast-rcnn时代冗余的代码，
 
&mdash;

**Comment by ChrisLee63** [comment]
现在可以跑一跑看看map。

**Comment by xiaolongDGitHub** [comment]
这么优秀的么！我来试试看看！
还能再请教个问题么，具有重叠视野中的两副图片中的相同的行人怎么匹配，或者利用这个person search 怎么做呢？

**Comment by ChrisLee63** [comment]
对每幅图片运行一次行人搜索网络，得到每个行人的box和feature。
然后对这两幅图片中的行人feature做一个匹配。
