### ISSUE TITLE
请问现在这个项目进行到什么程度了

### ISSUE THREAD

**Issue by mengfanda** [ChrisLee63/person_search#4]
你好，请问一下您的项目现在进行到什么程度是可以完成模型的训练了么，还是能够测试和运行demo。

**Comment by ChrisLee63** [comment]
可以训练，测试，demo。欢迎试用！

**Comment by mengfanda** [comment]
您好，我在训练程序的时候用了官方的resnet50_caffe.pth，出现了Missing key(s) in state_dict:错误，请问是因为什么问题呢?可否分享一下您的预训练模型

**Comment by ChrisLee63** [comment]
是我放在百度网盘里的那个模型吗？

**Comment by mengfanda** [comment]
您开题提供的预训练模型没有提供百度云密码

**Comment by mengfanda** [comment]
您提供的预训练模型没有提供百度云密码

**Comment by ChrisLee63** [comment]
抱歉，我的问题，马上就加上

**Comment by ChrisLee63** [comment]
现在试试？

**Comment by mengfanda** [comment]
感谢,用了预训练模型后现在可以正常训练了
