### ISSUE TITLE
Trained model google drive link

### ISSUE THREAD

**Issue by VishalKanakamamidi** [ChrisLee63/person_search#5]
Hey, Can you please share the google drive link for the trained model?

**Comment by kurehawaru** [comment]
Hi cool repo. I don't understand Chinese and I don't know how to get the trained model from the [link](https://pan.baidu.com/s/1dC8dEuB_8pV8m6Msrj8dXw) you provided (since it is written in Chinese). Can you share with us the google drive or explain how to obtain the trained model?

**Comment by ChrisLee63** [comment]
@VishalKanakamamidi 
@kurehawaru 
I am sorry. I will post the google drive link as soon as possible

**Comment by ChrisLee63** [comment]
Google drive link has been updated.
