### ISSUE TITLE
Need your email

### ISSUE THREAD

**Issue by khawar512** [ChrisLee63/person_search#7]
I am requesting you to please share your email address. I have to discussed that how you calculate results like mAP, Top1 and so on  on whole dataset

**Comment by ChrisLee63** [comment]
These code is from [https://github.com/ShuangLI59/person_search/blob/master/lib/datasets/psdb.py](url).

**Comment by khawar512** [comment]
right. Thank you. Do you know any similar repo for calculating mAP for face matching?

**Comment by ChrisLee63** [comment]
Sorry, I'm not familiar with facial matching.
mAP of the person search task is inspired by object detection.
You can see more details in the original paper.

**Comment by khawar512** [comment]
Ok. Thank you
