### ISSUE TITLE
单纯做ReID的一些问题

### ISSUE THREAD

**Issue by YuanXinCherry** [ChrisLee63/person_search#8]
想问一下，这个项目只在market和duke上做reid，如何训练和测试，训练对配置什么要求，大概需要多长时间训练？

**Comment by ChrisLee63** [comment]
测试阶段，把所有图片当成probe送入网络提取特征，然后计算相似度即可。
参考：https://github.com/ChrisLee63/person_search/blob/18f68235ca47a3c2025ce928f590be2758dc1454/tools/demo.py#L79
训练阶段，网络需要`img`, `img_info`, `gt_boxes`这三个信息，market和duke都能够提供，自己写个数据集处理模块即可。
参考：https://github.com/ChrisLee63/person_search/blob/18f68235ca47a3c2025ce928f590be2758dc1454/lib/datasets/psdb.py#L15
在CUHK-SYSU上训练大概要10-12个小时，一张1080ti就够了。
